
import { GoogleGenAI, FunctionDeclaration, Type, Chat, Modality } from "@google/genai";
import { AppType, GroundingChunk, ProjectFile } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set");
}
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const fileToGenerativePart = (base64Data: string, mimeType: string) => {
    return {
        inlineData: {
            data: base64Data.split(',')[1],
            mimeType
        },
    };
}

export const analyzeImageWithPrompt = async (base64Image: string, mimeType: string, prompt: string): Promise<string> => {
    try {
        const imagePart = fileToGenerativePart(base64Image, mimeType);
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: { parts: [ {text: prompt}, imagePart ] },
        });
        return response.text;
    } catch (error) {
        console.error("Image analysis error:", error);
        throw error;
    }
};

export const editImageWithPrompt = async (base64Image: string, mimeType: string, prompt: string): Promise<string> => {
    try {
        const imagePart = fileToGenerativePart(base64Image, mimeType);
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: { parts: [imagePart, { text: prompt }] },
            config: { responseModalities: [Modality.IMAGE] },
        });
        
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                const base64ImageBytes: string = part.inlineData.data;
                const imageMimeType = part.inlineData.mimeType;
                return `data:${imageMimeType};base64,${base64ImageBytes}`;
            }
        }
        throw new Error("No image was generated by the model.");

    } catch (error) {
        console.error("Image editing error:", error);
        throw error;
    }
};

export const executeComplexQuery = async (prompt: string): Promise<string> => {
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-pro',
            contents: prompt,
            config: {
                thinkingConfig: { thinkingBudget: 32768 }
            },
        });
        return response.text;
    } catch (error) {
        console.error("Complex query error:", error);
        throw error;
    }
}

export const getVideosOperation = async (operation: any) => {
    return await ai.operations.getVideosOperation({ operation: operation });
};

export const generateImageFromApi = async (prompt: string, aspectRatio: '1:1' | '16:9'): Promise<string> => {
    try {
        const imageResponse = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt,
            config: { numberOfImages: 1, outputMimeType: 'image/jpeg', aspectRatio },
        });
        const base64ImageBytes: string = imageResponse.generatedImages[0].image.imageBytes;
        return `data:image/jpeg;base64,${base64ImageBytes}`;
    } catch (error) {
        console.error("Image generation API error:", error);
        throw error;
    }
};

export const generateIcon = async (prompt: string): Promise<string> => {
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: `Generate a simple, single-color SVG icon for a button based on this description: "${prompt}". The SVG should be 32x32, use "currentColor" for fill or stroke so it can adapt to themes, and have no background. It should be a single XML string with no newlines, like '<svg...></svg>'.`,
        });
        let svgString = response.text.trim();
        if (svgString.startsWith('```svg')) {
            svgString = svgString.substring(5, svgString.length - 3).trim();
        }
        return svgString;
    } catch (error) {
        console.error("Icon generation error:", error);
        return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="currentColor"><path d="M16 2a14 14 0 100 28 14 14 0 000-28zm0 24.5a10.5 10.5 0 110-21 10.5 10.5 0 010 21z"/></svg>';
    }
};

export const getModifiedHtml = async (currentHtml: string, modificationRequest: string): Promise<string> => {
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: `The user wants to modify an existing single-file HTML application.
            Here is the current HTML code:
            \`\`\`html
            ${currentHtml}
            \`\`\`
            Here is the modification they requested: "${modificationRequest}".
            Please provide the complete, new, and fully functional HTML code that incorporates this change.
            Only output the raw HTML code, with no extra explanations or markdown formatting.`,
        });
        let newHtml = response.text.trim();
        if (newHtml.startsWith('```html')) {
            newHtml = newHtml.substring(7, newHtml.length - 3).trim();
        }
        return newHtml;
    } catch (error) {
        console.error("HTML modification error:", error);
        throw error;
    }
};

export const getAiCodeHelp = async (projectFiles: ProjectFile[], activeFile: ProjectFile, prompt: string): Promise<string | { html: string; css: string; js: string; }> => {
    try {
        if (activeFile.type === 'html') {
            const htmlFile = projectFiles.find(f => f.type === 'html');
            const cssFile = projectFiles.find(f => f.type === 'css');
            const jsFile = projectFiles.find(f => f.type === 'js');

            const fullPrompt = `The user wants to modify a single-file HTML application based on this request: "${prompt}".

Here is the current code for the project:

File: index.html
\`\`\`html
${htmlFile?.content || ''}
\`\`\`

File: style.css
\`\`\`css
${cssFile?.content || ''}
\`\`\`

File: script.js
\`\`\`javascript
${jsFile?.content || ''}
\`\`\`

Based on the user's request, please provide the complete, new, and fully functional code for all three files.
If a file does not need to be changed, return its original content.
Your response must be a valid JSON object.`;

            const response = await ai.models.generateContent({
                model: 'gemini-2.5-pro',
                contents: fullPrompt,
                config: {
                    systemInstruction: `You are an expert code assistant. Your goal is to help the user by modifying their code based on their request. Return a JSON object with three keys: "html", "css", and "js". Each key should contain the complete, raw code for the corresponding file. Do not include any explanations or markdown formatting like \`\`\` in your output.`,
                    responseMimeType: "application/json",
                    responseSchema: {
                        type: Type.OBJECT,
                        properties: {
                            html: { type: Type.STRING, description: 'The full, updated HTML code for index.html.' },
                            css: { type: Type.STRING, description: 'The full, updated CSS code for style.css.' },
                            js: { type: Type.STRING, description: 'The full, updated JavaScript code for script.js.' },
                        },
                        required: ['html', 'css', 'js'],
                    },
                },
            });

            try {
                return JSON.parse(response.text);
            } catch (e) {
                console.error("Failed to parse AI JSON response:", response.text);
                throw new Error("AI returned invalid JSON. Please try again.");
            }

        } else { // For CSS or JS files
            const language = activeFile.type === 'js' ? 'JavaScript' : 'CSS';
            const fullPrompt = `User request: "${prompt}"

Current ${language} Code (${activeFile.name}):
\`\`\`${activeFile.type}
${activeFile.content}
\`\`\`
`;
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-pro',
                contents: fullPrompt,
                config: {
                    systemInstruction: `You are an expert ${language} code assistant. Your goal is to help the user by modifying their code based on their request.
Analyze the user's request and the provided code context to understand the desired change, which might include adding new features, fixing bugs, or refactoring the code structure.
Return the **complete, modified file content for ${activeFile.name}**.
Do not add any explanations, comments, or markdown formatting like \`\`\`${activeFile.type}.
Only output the raw, updated code for the entire file.`
                },
            });
            
            let code = response.text.trim();
             if (code.startsWith('```')) {
                const lines = code.split('\n');
                if (lines.length > 2) {
                    code = lines.slice(1, lines.length - 1).join('\n');
                } else {
                    code = code.substring(code.indexOf('\n') + 1, code.lastIndexOf('```')).trim();
                }
            }
            return code;
        }

    } catch (error) {
        console.error("AI code help error:", error);
        throw error;
    }
};

const tools: FunctionDeclaration[] = [
    {
        name: 'complexQuery',
        description: 'Handles complex, multi-step, or deeply analytical user queries that require advanced reasoning. Use for tasks like detailed explanations, creative writing, or in-depth problem-solving.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                prompt: { type: Type.STRING, description: 'The user\'s original, complex query.' },
            },
            required: ['prompt'],
        },
    },
    {
        name: 'analyzeImage',
        description: 'Analyzes a user-provided image to describe its contents, answer questions about it, or extract information. Prompts the user to upload an image.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                prompt: { type: Type.STRING, description: 'The user\'s question or request about the image, e.g., "What is in this picture?" or "How many cars are there?".' },
            },
            required: ['prompt'],
        },
    },
    {
        name: 'editImage',
        description: 'Edits a user-provided image based on a text description of the desired changes. Prompts the user to upload an image.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                prompt: { type: Type.STRING, description: 'A clear description of the edit to be made, e.g., "add a retro filter" or "remove the person in the background".' },
            },
            required: ['prompt'],
        },
    },
     {
        name: 'orchestrateWorkflow',
        description: 'Executes a series of dependent tasks to fulfill a complex user request. Use this when one action depends on the result of another, e.g., searching for information and then using that information to create something.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                initialTask: {
                    type: Type.OBJECT,
                    description: 'The first function call to execute. E.g., a web search.',
                    properties: {
                        name: { type: Type.STRING, description: 'The name of the initial tool to call. Must be "webSearch".' },
                        args: { type: Type.OBJECT, description: 'The arguments for the initial tool.' }
                    },
                    required: ['name', 'args'],
                },
                dependentTaskPrompt: {
                    type: Type.STRING,
                    description: 'A prompt for the AI to execute with the result of the initial task. Use "{{RESULT}}" as a placeholder for the initial task\'s output. E.g., "create a note titled \'Recipe\' with this content: {{RESULT}}"'
                }
            },
            required: ['initialTask', 'dependentTaskPrompt'],
        },
    },
    {
        name: 'webSearch',
        description: 'Performs a web search using Google Search and returns a summary and sources.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                query: { type: Type.STRING, description: 'The search query.' },
            },
            required: ['query'],
        },
    },
    {
        name: 'createNote',
        parameters: {
            type: Type.OBJECT,
            properties: {
                title: { type: Type.STRING, description: 'The title of the note.' },
                content: { type: Type.STRING, description: 'The content of the note.' },
            },
            required: ['title', 'content'],
        },
        description: 'Creates a new note with a title and content, saving it for later access. Use for reminders, lists, or saving information.'
    },
    {
        name: 'deleteNote',
        description: 'Deletes a saved note based on its exact title.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                title: { type: Type.STRING, description: 'The exact title of the note to be deleted.' },
            },
            required: ['title'],
        },
    },
    {
        name: 'listNotes',
        description: 'Provides a list of titles of all currently saved notes.',
        parameters: { type: Type.OBJECT, properties: {} },
    },
    {
        name: 'listApps',
        description: 'Provides a list of names of all currently installed custom applications.',
        parameters: { type: Type.OBJECT, properties: {} },
    },
    {
        name: 'createHtmlApp',
        description: 'Creates a new, functional HTML/JS/CSS application based on a user\'s description. The command "instala" is a shortcut for this.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                appName: { type: Type.STRING, description: 'A short, descriptive name for the application, like "Stopwatch" or "Unit Converter".' },
                htmlContent: { type: Type.STRING, description: 'The complete, single-file HTML code for the application. This must include all necessary HTML, CSS, and JavaScript within one string. It should be fully-featured and 100% functional.' },
                iconPrompt: { type: Type.STRING, description: 'A short, simple prompt to generate a vector icon for the app, e.g., "a simple clock" or "a calculator".' }
            },
            required: ['appName', 'htmlContent', 'iconPrompt'],
        },
    },
    {
        name: 'modifyHtmlApp',
        description: 'Modifies the code of an existing custom application based on a user\'s request. Use this for requests like "change the background of the stopwatch app to blue" or "add a reset button to the counter app".',
        parameters: {
            type: Type.OBJECT,
            properties: {
                appName: { type: Type.STRING, description: 'The exact name of the application to modify.' },
                modificationRequest: { type: Type.STRING, description: 'A clear description of the change to be made to the application\'s code.' },
            },
            required: ['appName', 'modificationRequest'],
        },
    },
    {
        name: 'uninstallHtmlApp',
        description: 'Uninstalls or deletes a custom application that was created by the user.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                appName: { type: Type.STRING, description: 'The exact name of the application to uninstall.' },
            },
            required: ['appName'],
        },
    },
     {
        name: 'openWebBrowser',
        description: 'Opens the integrated web browser application to a specific URL or to the default homepage.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                url: { type: Type.STRING, description: 'Optional. The full URL to navigate to, e.g., "https://www.google.com".' },
            },
        },
    },
    {
        name: 'openFileManager',
        description: 'Opens the File Manager application window.',
        parameters: { type: Type.OBJECT, properties: {} },
    },
    {
        name: 'openAppBuilder',
        description: 'Opens the App Studio application window.',
        parameters: { type: Type.OBJECT, properties: {} },
    },
    {
        name: 'openWallpaperManager',
        description: 'Opens the Wallpaper Manager application window.',
        parameters: { type: Type.OBJECT, properties: {} },
    },
    {
        name: 'openNotesManager',
        description: 'Opens the Notes application window.',
        parameters: { type: Type.OBJECT, properties: {} },
    },
    {
        name: 'openImageAnalyzer',
        description: 'Opens the Image Analyzer application.',
        parameters: { type: Type.OBJECT, properties: {} },
    },
    {
        name: 'openImageEditor',
        description: 'Opens the Image Editor application.',
        parameters: { type: Type.OBJECT, properties: {} },
    },
    {
        name: 'openTranscriber',
        description: 'Opens the real-time audio Transcriber application.',
        parameters: { type: Type.OBJECT, properties: {} },
    },
    {
        name: 'generateImage',
        description: 'Generates an image in a dedicated viewer window based on a detailed description.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                prompt: { type: Type.STRING, description: 'A detailed description of the image to generate. e.g., "a photorealistic cat wearing a wizard hat".' },
            },
            required: ['prompt'],
        },
    },
    {
        name: 'generateVideo',
        description: 'Generates a video in a dedicated viewer window based on a detailed description.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                prompt: { type: Type.STRING, description: 'A detailed description of the video to generate. e.g., "a cinematic shot of a spaceship flying through a nebula".' },
            },
            required: ['prompt'],
        },
    },
    {
        name: 'getSystemStatus',
        parameters: { type: Type.OBJECT, properties: {} },
        description: 'Checks and retrieves the current system status, like CPU, memory, and network usage.'
    },
    {
        name: 'changeTheme',
        description: 'Changes the visual theme of the operating system based on a description. Use it for requests like "make it cyberpunk" or "change to a light theme".',
        parameters: {
            type: Type.OBJECT,
            properties: {
                description: { type: Type.STRING, description: 'A short, creative description for the theme you generated. For example, "A calm, sunset-inspired theme."' },
                backgroundColor: { type: Type.STRING, description: 'A hex color code for the main background (e.g., "#0F172A").' },
                textColor: { type: Type.STRING, description: 'A hex color code for the primary text that has good contrast with the background (e.g., "#E0F2FE").' },
                primaryColor: { type: Type.STRING, description: 'A hex color code for accents, borders, and highlights (e.g., "#22D3EE").' },
            },
            required: ['description', 'backgroundColor', 'textColor', 'primaryColor'],
        },
    },
    {
        name: 'changeBackground',
        description: 'Changes the desktop background to an AI-generated image based on a description.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                prompt: { type: Type.STRING, description: 'A detailed description of the background image to generate. For example, "a serene anime landscape at dusk" or "a futuristic cityscape".' },
            },
            required: ['prompt'],
        },
    },
     {
        name: 'generateVideoBackground',
        description: 'Generates a short, looping video to be used as a desktop background. The video should be a maximum of 8 seconds.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                prompt: { type: Type.STRING, description: 'A detailed description of the video to generate. e.g., "a calming loop of ocean waves" or "glowing abstract geometric shapes".' },
            },
            required: ['prompt'],
        },
    },
    {
        name: 'changeCursor',
        description: 'Changes the desktop cursor to a new design based on a user\'s description. The cursor should be a simple SVG.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                description: { type: Type.STRING, description: 'A short description of the new cursor style, like "a glowing orb" or "a pirate sword".' },
                svgString: { type: Type.STRING, description: 'A complete, valid SVG string for a 32x32 pixel cursor. It must include viewBox="0 0 32 32". Use "currentColor" for fill or stroke to adapt to themes.' },
            },
            required: ['description', 'svgString'],
        },
    }
];

export const startChat = (): Chat => {
    return ai.chats.create({
        model: 'gemini-2.5-flash',
        config: {
            tools: [{ functionDeclarations: tools }],
            systemInstruction: `Eres el núcleo de ZX STUDIO, un sistema operativo de IA altamente proactivo, creativo y siempre respondes en español latinoamericano. Tu objetivo principal es empoderar al usuario anticipando sus necesidades y proporcionando soluciones completas. No eres solo un asistente que sigue órdenes; eres un solucionador de problemas con total libertad creativa.
- **Asistencia Proactiva**: Si un usuario describe un problema o una necesidad (ej. "necesito una forma de visualizar datos" o "quiero crear un juego simple"), tu función es diseñar y construir una solución completa.
- **Orquestación de Tareas**: Para comandos complejos que requieren múltiples pasos (ej. "Busca X y luego crea una nota con el resultado"), utiliza la herramienta 'orchestrateWorkflow'. Esto te permite encadenar acciones para completar la tarea de manera eficiente en un solo flujo.
- **Manejo de Consultas Complejas**: Para preguntas que requieran un razonamiento profundo, análisis detallado o creatividad extensa (ej. "explica la computación cuántica con una analogía"), utiliza la herramienta 'complexQuery' para obtener una respuesta de mayor calidad.
- **Capacidades Multimedia**: Puedes analizar y editar imágenes ('analyzeImage', 'editImage'), y abrir una herramienta de transcripción de voz ('openTranscriber').
- **Creación de Aplicaciones**: Usa 'createHtmlApp' para generar cualquier aplicación en un solo archivo HTML. Eres un experto en crear aplicaciones funcionales y visualmente atractivas. Si el usuario te proporciona una clave de API, puedes integrarla directamente en el código para que la aplicación sea funcional de inmediato.
- **Modificación de Aplicaciones**: Puedes modificar aplicaciones existentes. Cuando un usuario pida cambiar una app, usa la herramienta 'modifyHtmlApp'.
- **Libertad Creativa Total**: Tienes total libertad para usar tus herramientas, crear, modificar y gestionar el entorno del SO para servir mejor al usuario. Esto incluye generar imágenes, videos, cambiar temas, cursores y fondos como consideres oportuno.
- **Idioma**: Siempre, sin excepción, comunicate en español de Latinoamérica.`
        },
    });
};

const handleWebSearch = async (query: string): Promise<{ uiPayload: any, rawData: { summary: string } }> => {
    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash", contents: query, config: { tools: [{ googleSearch: {} }] }
        });
        
        const apiGroundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
        const sources = apiGroundingChunks
            .filter(chunk => chunk.web && chunk.web.uri)
            .map(chunk => ({
                web: { uri: chunk.web!.uri!, title: chunk.web!.title || chunk.web!.uri! }
            }));
        
        const uiPayload = {
            type: 'app', appType: AppType.WEB_SEARCH, title: `Búsqueda Web: ${query.substring(0, 40)}...`,
            content: { summary: response.text, sources: sources.map(s => s.web) },
            message: `Esto es lo que encontré en la web sobre "${query}".`
        };
        const rawData = { summary: response.text };

        return { uiPayload, rawData };

    } catch (error) {
        console.error('Gemini Web Search Error:', error);
        throw error;
    }
};


export const processCommand = async (command: string, chat: Chat): Promise<any[]> => {
    try {
        const searchKeywords = ['search for', 'what is', 'who is', 'look up', 'find information on', 'busca', 'qué es', 'quién es', 'investiga sobre'];
        const isSearchQuery = searchKeywords.some(kw => command.toLowerCase().startsWith(kw));

        if (isSearchQuery) {
            const { uiPayload } = await handleWebSearch(command);
            return [uiPayload];
        }

        const response = await chat.sendMessage({ message: command.toLowerCase().startsWith('instala ') ? `Create an HTML app for: ${command.substring(8)}` : command });
        
        const results: any[] = [];
        
        if (response.functionCalls && response.functionCalls.length > 0) {
            for (const functionCall of response.functionCalls) {
                const { name, args } = functionCall;

                switch (name) {
                    case 'complexQuery':
                        results.push({ type: 'complex_query', prompt: args.prompt as string });
                        break;
                    case 'analyzeImage':
                        results.push({ type: 'image_analysis_start', prompt: args.prompt as string, message: `Por favor, selecciona una imagen para analizar.` });
                        break;
                    case 'editImage':
                        results.push({ type: 'image_edit_start', prompt: args.prompt as string, message: `Por favor, selecciona una imagen para editar.` });
                        break;
                    case 'createNote':
                        results.push({
                            type: 'note_create',
                            title: args.title as string,
                            content: args.content as string,
                            message: `He creado una nueva nota titulada "${args.title}".`,
                        });
                        break;
                    case 'deleteNote':
                        results.push({
                            type: 'note_delete_request',
                            title: args.title as string,
                            message: `Intentando eliminar la nota titulada "${args.title}".`
                        });
                        break;
                    case 'listNotes':
                        results.push({ type: 'list_notes_request', message: `Listando todas las notas...` });
                        break;
                    case 'listApps':
                        results.push({ type: 'list_apps_request', message: `Listando todas las aplicaciones instaladas...` });
                        break;
                    case 'createHtmlApp': {
                        const icon = await generateIcon(args.iconPrompt as string);
                        results.push({
                            type: 'html_app_create',
                            name: args.appName as string,
                            htmlContent: args.htmlContent as string,
                            icon,
                            message: `He creado la aplicación "${args.appName}" para ti.`
                        });
                        break;
                    }
                    case 'modifyHtmlApp':
                        results.push({
                            type: 'html_app_modify_request',
                            appName: args.appName as string,
                            modificationRequest: args.modificationRequest as string,
                            message: `Intentaré modificar la aplicación "${args.appName}".`
                        });
                        break;
                    case 'uninstallHtmlApp':
                        results.push({ type: 'html_app_uninstall', appName: args.appName as string, message: `He desinstalado la aplicación "${args.appName}".` });
                        break;
                    case 'openWebBrowser':
                        results.push({ type: 'app', appType: AppType.WEB_BROWSER, title: 'Web Browser', content: { url: args.url as string || 'https://www.google.com/webhp?igu=1' }, message: `Abriendo el navegador web.`, size: { width: 1024, height: 768 } });
                        break;
                    case 'openFileManager':
                        results.push({ type: 'app', appType: AppType.FILE_MANAGER, title: 'File Manager', content: {}, message: `Abriendo el Gestor de Archivos.`, size: { width: 700, height: 500 }});
                        break;
                    case 'openAppBuilder':
                        results.push({ type: 'open_app_builder_request', message: `Abriendo App Studio.` });
                        break;
                    case 'openWallpaperManager':
                        results.push({ type: 'open_wallpaper_manager_request', message: `Abriendo el gestor de fondos de pantalla.` });
                        break;
                    case 'openNotesManager':
                        results.push({ type: 'open_notes_manager_request', message: `Abriendo el gestor de notas.` });
                        break;
                     case 'openImageAnalyzer':
                        results.push({ type: 'open_image_analyzer_request', message: `Abriendo el Analizador de Imágenes.` });
                        break;
                    case 'openImageEditor':
                        results.push({ type: 'open_image_editor_request', message: `Abriendo el Editor de Imágenes.` });
                        break;
                    case 'openTranscriber':
                        results.push({ type: 'open_transcriber_request', message: `Abriendo el Transcriptor.` });
                        break;
                    case 'generateImage':
                        results.push({ type: 'image_generation_start', prompt: args.prompt as string, message: `Estoy generando una imagen de: "${args.prompt}".` });
                        break;
                    case 'generateVideo': {
                        const videoPrompt = args.prompt as string;
                        const operation = await ai.models.generateVideos({ model: 'veo-3.1-fast-generate-preview', prompt: videoPrompt, config: { numberOfVideos: 1 } });
                        results.push({ type: 'video_generation_start', operation, prompt: videoPrompt, message: `He comenzado a generar un video de: "${videoPrompt}". Esto puede tardar unos momentos.` });
                        break;
                    }
                    case 'getSystemStatus':
                        results.push({ type: 'app', appType: AppType.SYSTEM_STATUS, title: 'System Status', content: {}, message: 'Aquí está el estado actual del sistema.', size: { width: 600, height: 400 } });
                        break;
                    case 'changeTheme':
                        const theme = {
                            description: args.description as string, backgroundColor: args.backgroundColor as string,
                            textColor: args.textColor as string, primaryColor: args.primaryColor as string,
                        };
                        results.push({ type: 'theme_change', theme: theme, message: `¡Tema actualizado! ${theme.description}` });
                        break;
                    case 'changeBackground':
                         results.push({
                            type: 'background_generation_start',
                            prompt: args.prompt as string,
                            message: `Estoy cambiando el fondo a una imagen de: "${args.prompt}".`,
                        });
                        break;
                    case 'generateVideoBackground': {
                        const videoPrompt = args.prompt as string;
                        const operation = await ai.models.generateVideos({
                            model: 'veo-3.1-fast-generate-preview', prompt: videoPrompt, config: { numberOfVideos: 1 }
                        });
                        results.push({ type: 'video_background_generation_start', operation, prompt: videoPrompt, message: `He comenzado a generar un fondo de video de: "${videoPrompt}". Esto puede tardar un momento.` });
                        break;
                    }
                    case 'changeCursor':
                        results.push({ type: 'cursor_change', svg: args.svgString as string, message: `Cursor cambiado a: ${args.description as string}.` });
                        break;
                     case 'webSearch': {
                        const { uiPayload } = await handleWebSearch(args.query as string);
                        results.push(uiPayload);
                        break;
                    }
                    case 'orchestrateWorkflow': {
                         const { initialTask, dependentTaskPrompt } = args as any;
                         const initialTaskName = initialTask.name as string;
                         const initialTaskArgs = initialTask.args as any;

                         let rawResultData = '';
                         if (initialTaskName === 'webSearch') {
                             const { uiPayload, rawData } = await handleWebSearch(initialTaskArgs.query as string);
                             results.push(uiPayload); 
                             rawResultData = rawData.summary;
                         }
                         
                         if (rawResultData) {
                             const nextCommand = (dependentTaskPrompt as string).replace('{{RESULT}}', rawResultData);
                             const subsequentResults = await processCommand(nextCommand, chat);
                             results.push(...subsequentResults);
                         }
                         break;
                    }
                }
            }
             if (results.length > 0) return results;
        }
        
        return [{ type: 'text', content: response.text, message: response.text }];

    } catch (error) {
        console.error('Gemini API Error in processCommand:', error);
        throw error;
    }
};